services:
    mongo:
        image: mongo:8

        restart: unless-stopped

        ports:
            - '27017:27017'

        volumes:
            - mongo-data:/data/db

        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    playwright:
        build: .

        depends_on:
            mongo:
                condition: service_healthy

        env_file:
            - .env.docker

        environment:
            ENV_FILE: .env.docker

        volumes:
            - ./playwright-report:/app/playwright-report
            - ./test-results:/app/test-results
            - ./allure-results:/app/allure-results
            - ./tests:/app/tests

        command: npx playwright test

volumes:
    mongo-data:
