version: '3.9'

services:

  playwright:

    build: .

    container_name: playwright-framework

    env_file:
      - .env

    environment:
      MONGO_URI: mongodb://host.docker.internal:27017

    volumes:
      - ./playwright-report:/app/playwright-report

    command: npx playwright test